CREATE TABLE IF NOT EXISTS contact (
  id SERIAL PRIMARY KEY,
  email VARCHAR(254) NOT NULL,
  name VARCHAR(100),
  message TEXT NOT NULL,
  user_ip TEXT NOT NULL,
  submitted_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
